[matching]
'obsidian' = 'ï¥'
'firefox' = 'î€‡'
'KeePass2' = 'ï„¾'
'org.keepassxc.KeePassXC' = 'ï„¾'
'betterbird' = 'ïƒ '
'Mattermost' = 'ğŸ§­'
'eu.betterbird.Betterbird' = 'ïƒ '
'com.saivert.pwvucontrol' = 'ï€¨'
'signal' = 'ï‰º'
'nwg-displays' = 'î…£'
'org.kde.gwenview' = 'ïŒ‚'
'imv' = 'ï€¾'
'/Yazi:/' = 'ï…›'
'/yay/' = 'ï‚­'
'/updateall/' = 'ï‚­'
'/rsync/' = 'ïƒ…'
'/python/' = 'ï¢'
'org.strawberrymusicplayer.strawberry' = 'ï‹'
'/nvim ?\w*/' = 'ï‰½'
'/htop/' = 'ïš‚'
'kitty' = 'ï„ '
'libreoffice-writer' = 'ï‡‚'
'libreoffice-calc' = 'ï‡ƒ'
'io.github.Qalculate.qalculate-qt' = 'ï‡¬'
'blueman-manager' = 'ïŠ“'
'code' = 'ğŸ’»'
'/GNU Image Manipulation Program/' = 'ï‡…'
'org.kde.okular' = 'ï‡'
'evince' = 'ï‡'
'sonic-visualiser' = 'âˆ¿'
'org.inkscape.Inkscape' = 'ï—‹'
'org.wireshark.Wireshark' = 'ï–'
'nm-connection-editor' = 'ï›¿'
'nm-applet' = 'ï›¿'
