[[profile]]
name = "standalone"
exec = ["notify-send shikane \"Profile $SHIKANE_PROFILE_NAME has been applied\"", "nmcli radio wifi on", "~/.swayidle/restart.bash"]

[[profile.output]]
enable = true
search = ["m=0x414B", "s=", "v=Lenovo Group Limited"]
mode = "2880x1800@120Hz"
position = "0,0"
scale = 1.796875
transform = "normal"
adaptive_sync = false

[[profile]]
name = "HO426_lidClosed"
exec = ["notify-send shikane \"Profile $SHIKANE_PROFILE_NAME has been applied\"", "nmcli radio wifi off", "~/.swayidle/restart.bash -C ~/.swayidle/dock-config", "pactl set-default-sink alsa_output.pci-0000_c4_00.1.HiFi__HDMI1__sink"]

[[profile.output]]
enable = true
search = ["m=S27B80T", "s=HCJX800132", "v=Samsung Electric Company"]
mode = "3840x2160@59.997Hz"
position = "0,0"
scale = 1.59765625
transform = "normal"
adaptive_sync = false

[[profile.output]]
enable = false
search = ["m=0x414B", "s=", "v=Lenovo Group Limited"]

[[profile]]
name = "HO426_lidOpen"
exec = ["notify-send shikane \"Profile $SHIKANE_PROFILE_NAME has been applied\"", "nmcli radio wifi off", "~/.swayidle/restart.bash", "pactl set-default-sink alsa_output.pci-0000_c4_00.1.HiFi__HDMI1__sink"]

[[profile.output]]
enable = true
search = ["m=S27B80T", "s=HCJX800132", "v=Samsung Electric Company"]
mode = "3840x2160@59.997Hz"
position = "0,0"
scale = 1.59765625
transform = "normal"
adaptive_sync = false

[[profile.output]]
enable = true
search = ["m=0x414B", "s=", "v=Lenovo Group Limited"]
mode = "2880x1800@120Hz"
position = "2400,350"
scale = 1.796875
transform = "normal"
adaptive_sync = false

[[profile]]
name = "P621_noLid"
exec = ["notify-send shikane \"Profile $SHIKANE_PROFILE_NAME has been applied\"", "nmcli radio wifi off", "nmcli con up \"Uni\"", "~/.swayidle/restart.bash -C ~/.swayidle/dock-config"]

[[profile.output]]
enable = true
search = ["m=LEN P27h-10", "s=0x01010101", "v=Lenovo Group Limited"]
mode = "2560x1440@59.951Hz"
position = "2560,0"
scale = 1.0
transform = "normal"
adaptive_sync = false

[[profile.output]]
enable = false
search = ["m=0x054F", "s=", "v=LG Display"]

[[profile.output]]
enable = true
search = ["m=LEN P27h-10", "s=0x01010101", "v=Lenovo Group Limited"]
mode = "2560x1440@59.951Hz"
position = "0,0"
scale = 1.0
transform = "normal"
adaptive_sync = false

[[profile]]
name = "Frye_single"
exec = ["notify-send shikane \"Profile $SHIKANE_PROFILE_NAME has been applied\"", "nmcli radio wifi on", "~/.swayidle/restart.bash"]

[[profile.output]]
enable = true
search = ["m=0x054F", "s=", "v=LG Display"]
mode = "1920x1080@60.02Hz"
position = "0,0"
scale = 1.0
transform = "normal"
adaptive_sync = false

[[profile]]
name = "Lab_Dell"

[[profile.output]]
enable = false
search = ["m=0x414B", "s=", "v=Lenovo Group Limited"]

[[profile.output]]
enable = true
search = ["m=DELL U2211H", "s=D1TPK12HA3RL", "v=Dell Inc."]
mode = "1920x1080@60Hz"
position = "0,0"
scale = 1.0
transform = "normal"
adaptive_sync = false

[[profile]]
name = "HO009"

[[profile.output]]
enable = true
search = ["m=VP-4XX", "s=0x00000030", "v=Kramer Electronics Ltd. International"]
mode = "1920x1080@60Hz"
position = "0,0"
scale = 1.0
transform = "normal"
adaptive_sync = false

[[profile.output]]
enable = true
search = ["m=0x414B", "s=", "v=Lenovo Group Limited"]
mode = "1920x1080@120Hz"
position = "0,0"
scale = 1.0
transform = "normal"
adaptive_sync = false

